spring:
  application:
    name: gateway-service

server:
  port: 8080

discovery:
  server:
    url: http://discovery-service:8761

management:
  endpoints:
    web:
      exposure:
        include: "*"